run_mode: debug #debug release test

log:
  filename: logs/gin.log
  level: debug  #debug info warn error panic fatal
  maxsize: 10
  maxbackup: 3
  maxage: 28
  compress: false

server:
  port : 8080
  read-timeout : 60
  write-timeout : 60

database:
  type : mysql
  user : yulv
  password : 123456
  host : 192.168.91.100:3306
  name : yulv
  table-prefix :

rbac:
  model: etc\basic_model.conf
  policy: etc\basic_policy.csv
  auth: etc\auth.json

app:
  page-size: 10
  adminpassword: '123456'

cache: memory
redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0
  key_prefix: /admin/

memory:
  purge_time: 60 # seconds

elasticsearch:
  host: http://192.168.91.100:9200
  access-index: yulv_access
  rule-index: yulv_rule
  timeout: 5s
  user: elastic
  password: changme